version: "2"
services:
  db:
    image: postgres:9.6.2
    ports:
      - 5432
    volumes: 
      - /var/lib/docker-data:/var/lib
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "${VERSION}"
    env_file:
      - web-variables.env
    ports:
      - "4001:4001"
    depends_on:
      - db
    entrypoint: ./wait-for-it.sh db:5432 -- bin/notebook foreground
