version: "2"
services:
  db:
    image: postgres
    ports:
      - 5432
    volumes: 
      - /var/lib/docker-data:/var/lib
  web:
    build:
      context: .
      args:
        VERSION: "${VERSION}"
    env_file:
      - web-variables.env
    ports:
      - "80:8888"
    depends_on:
      - db

